[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.115.12",
    "lxml>=5.4.0",
    "pydantic>=2.11.4",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.34.2",
]
