planner_agent:
  memory_limit: 1000  # Maximum number of memories to store
  retry_cap: 3  # Maximum number of retries for failed operations
  timeout: 300  # Operation timeout in seconds
  capabilities:
    - planning
    - goal_decomposition
    - resource_allocation
  metadata:
    description: "Agent responsible for planning and decomposing goals into subtasks"
    priority: 1

refiner_agent:
  memory_limit: 800
  retry_cap: 2
  timeout: 180
  capabilities:
    - refinement
    - optimization
    - validation
  metadata:
    description: "Agent responsible for refining and optimizing plans"
    priority: 2 