# API Gateway Configuration

# Rate Limiting Configuration
rate_limit:
  requests_per_minute: 60
  burst_size: 10
  window_size: 60  # seconds
  block_duration: 300  # seconds

# Security Configuration
security:
  jwt_secret: "your-secret-key-here"  # Change this in production
  jwt_expiry: 3600  # seconds
  api_key_rotation_days: 30
  encryption_key: "your-encryption-key-here"  # Change this in production
  allowed_origins:
    - "http://localhost:8000"
    - "http://localhost:8001"
    - "http://localhost:8002"
  ssl_enabled: true

# API Configuration
api:
  version: "v1"
  base_path: "/api"
  timeout: 30  # seconds
  max_request_size: 10485760  # 10MB
  cache_ttl: 300  # seconds

# Public Endpoints (no authentication required)
public_endpoints:
  - "health_check"
  - "metrics"
  - "docs"

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""  # Set in production
  ssl: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/api_gateway.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Metrics Configuration
metrics:
  collection_interval: 60  # seconds
  retention_days: 7
  alert_thresholds:
    error_rate: 5  # percentage
    response_time: 1.0  # seconds
    rate_limit_hits: 10  # per minute

# Caching Configuration
caching:
  enabled: true
  default_ttl: 300  # seconds
  max_size: 104857600  # 100MB
  strategies:
    - name: "response_cache"
      ttl: 300
    - name: "rate_limit"
      ttl: 60
    - name: "api_keys"
      ttl: 86400  # 24 hours

# Performance Configuration
performance:
  connection_pool_size: 10
  max_connections: 100
  timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 1  # seconds

# Data Management Configuration
data_management:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  compression:
    enabled: true
    level: 6
  validation:
    enabled: true
    max_depth: 10
    max_items: 1000

# Monitoring Configuration
monitoring:
  enabled: true
  endpoints:
    - path: "/health"
      interval: 30  # seconds
    - path: "/metrics"
      interval: 60  # seconds
  alerts:
    email:
      enabled: false
      recipients: []
    slack:
      enabled: false
      webhook_url: ""
    pagerduty:
      enabled: false
      service_key: "" 