mission_system:
  # Storage configuration
  storage:
    missions_dir: "missions"
    backup_dir: "missions/backups"
    max_backups: 10
    backup_interval: 3600  # seconds
    
  # Queue configuration
  queue:
    max_size: 1000
    timeout: 300  # seconds
    retry_attempts: 3
    retry_delay: 60  # seconds
    
  # Task processing
  task_processing:
    max_concurrent_tasks: 10
    task_timeout: 3600  # seconds
    cleanup_interval: 86400  # seconds
    
  # Mission processing
  mission_processing:
    max_concurrent_missions: 5
    mission_timeout: 86400  # seconds
    cleanup_interval: 86400  # seconds
    
  # Logging configuration
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/mission_system.log"
    max_size: 10485760  # 10MB
    backup_count: 5
    
  # Monitoring configuration
  monitoring:
    enabled: true
    metrics_interval: 60  # seconds
    alert_thresholds:
      task_failure_rate: 0.1  # 10%
      mission_failure_rate: 0.05  # 5%
      queue_size_threshold: 0.8  # 80%
      
  # Security configuration
  security:
    encryption:
      enabled: true
      key_rotation_interval: 86400  # seconds
    authentication:
      required: true
      token_expiry: 3600  # seconds
      
  # Performance configuration
  performance:
    cache:
      enabled: true
      ttl: 300  # seconds
      max_size: 1000
    connection_pool:
      max_size: 10
      timeout: 30  # seconds
      
  # Default values
  defaults:
    mission:
      priority: 0
      timeout: 86400  # seconds
    task:
      priority: 0
      timeout: 3600  # seconds
      max_retries: 3
      retry_delay: 60  # seconds 